[package]
name = "scs-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rosc = "0.10"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

